### ISSUE TITLE
Runtime Cleanup

### ISSUE THREAD

**Issue by isbm** [Elektrobit/oci-pilot#32]
# The Problem

Unlike read-only Canonical Snaps (squashfs), Flakes has two modes:
- **Read-only**
  Just like snaps. Data may be stored outside somewhere.

- **Read-write**
  Data may be also stored outside, but the Flake's state itself can be modified independently.

When Flake is finished its runtime, logically always to remove it. This prevents pollution of useless *instance* images. This is ideal for just a software, which runs in a container, but looks like it is just a native software. So far, so good: same behaviour as with the Snaps.

However, what to do if a Flake is _internally_ modified and user wants that to be persisted for a certain period of time? An example: a development environment of a different hardware architecture with a Git code inside or a deployed system?

# The Expectations

Read-write Flakes are rather exception than a mainstream. Because the data still can be stored outside with no harm to the flow and immutable is still better. However, some cases might require read-write Flake, like a confined package build to ensure nothing wrong is linked in the process. Such Flake can be used for further debugging of a failing package, for example.

The expectation is that a user, who is using Flakes (not podman directly!) is automatically helped to cleanup the mess left behind of a dangling container instances.

Of course, manual cleanup is possible. But this path should not be required, because the main purpose of Flakes is to hide the OCI engine at first place.

# The Solution?

1. **Limit read-write use and make all read-only behaviour by default**
Currently `engine.yml` is all "up to user". It is OK, as long as a packager knows what he is doing and 100% sure he is not doing anything wrong by _not adding_ `--rm` to the options (remove after quit). Probably we need engine wrappers, which will add cleanup always by default, unless _explicitly_ turned off in the same `engine.yml` configuration, like:

```yaml
# Explicitly say the Flake is mutable. If omitted, "immutable" by default.
type: mutable

# The usual runtime config
runtime:
  podman:
    ...
```

2. **Force mutable Flakes to be always reused**
Since making mutable Flake and then cleaning it all up makes no sense, then in case a Flake is mutable, for `podman` engine `--rm` should be always removed. If found in a config, a flake should quit with an error of mis-packaging. Example behaviour of Flake-delivered Python (mock-up):

```
$ python
Packaging error: Flake is mutable, but you ask to remove its instance on finish.
Either define it immutable or do not explicitly remove it.
```

3. **Allow instance cleanup** (see the Open Issues, mainly)

Read-write _instances_ brings a problem of "Always at least one instance left" (for the reuse). So the problem is not just if a user launches a new read-write Flake 1000 times, but also if a user launches 1000 read-write different Flakes at least one time.

A possible solution to prevent overbloating the system is to force the user to look after his Flakes. For example, a config of the Pilot itself anywhere in `/etc/oci-pilot.conf` for a quota limit, something like:

```yaml
# Limit instances per a user
instances-per-user: 100

# Purge dangling instances those were not accessed more than 60 days
instances-timeout: 60 d
```

In case user wants 101th, `oci-pilot` should abort a flake and suggest cleaning up the instances (with either `podman` directly or other ways). Practically none of read-write Flakes would be launch-performance critical. Therefore every time any read-write (!) Flake is launched, it should check for outdated instances as well and pre-purge them first, and only then launch a target Flake. It will surely for time to time impacts a performance on a very messy system, but that's OK.

Read-only Flakes, those are equivalents to Snaps, should not do this check due to performance savings.

# The Open Issues

## Handling multiple instances of one mutable Flake

This is sort of `podman ps` already... The use-case of this would be very limited. Possible solutions are:
- Do not support this. 😉 
- Add `flake` option that will operate instances

In case of `flake` option, each flake will have it wrapped before any other options, e.g.:

```
$ aarch64-dev-env flake --help
  new=[NAME]     Launch a new instance. Optionally specify a name.
  resume=<NAME>  Resume an existing instance explicitly to a precise name.
  args ....      Add arguments, those are native to an application
```

Calling `aarch64-dev-env` alone will just create one instance of a read-write Flake. Quitting it and calling it again will:
- Resume a container
- Attach back to its ID in background

In case user wants _another_ instance from this, then something like:

```
$ aarch64-dev-env flake new
```

However, this leaves a question to which flake one should re-attach back on a next run? One way is to specify the Podman's name (or ID):

```
$ aarch64-dev-env
Multiple Flake instances detected. Which one to re-attach?
(1) Stinky_Sniffer
(2) Bombastic_Bummer

Enter a number: _
```

Or this way:

```
$ aarch64-dev-env flake resume=Stinky_Sniffer
```

This can be used in scripts, when `new` can have a name, like:

```
$ aarch64-dev-env flake new=Junky_Jack
```

...and then `resume=Junky_Jack` later in the script.

Limitation of this approach is that when explicitly using `flake` argument, there is a need for complex arguments interface, where e.g. `args` would be native to the Flake arguments. I.e. `python -c 'print("Hi")'` would be done like:

    $ python flake new=Pimpy_Punk args -c 'print("Hi")'

The above would call a Python read-write'able Flake with the usual arguments into a new instance `Pimpy_Punk`, also visible under Podman `ps`.

**Comment by isbm** [comment]
@schaefi it is now looks more like a full-blown RFC... 🤦🏼

**Comment by schaefi** [comment]
> A possible solution to prevent overbloating the system is to force the user to look after his Flakes. For example, a config of the Pilot itself anywhere in /etc/oci-pilot.conf for a quota limit, something like:

iirc podman has its own quota system to manage the number of containers running. I'm not so keen on implementing that big-brother-is-watching as part of the simple oci-pilot launcher concept. To do this we would also need to introduce a background daemon checking the state. To be honest I don't see this to be a responsibility of oci-pilot

> # Explicitly say the Flake is mutable. If omitted, "immutable" by default.
> type: mutable

Hmm, if a container is mutable or immutable you can configure in the runtime setting of the flake, e.g

* immutable:

    ```yaml
    podman:
      runtime:
        - --read-only
    ```

* with quota
 
    ```yaml
    podman:
      runtime:
        - --storage-opt size=10G
    ```

**Comment by schaefi** [comment]
The ability to resume/restart and attach back to a container instance I have now added. This does not complete all of the stuff you talked about but is a start and all this should be done in small and clean steps

**Comment by schaefi** [comment]
>However, this leaves a question to which flake one should re-attach back on a next run? One way is to specify the Podman's name (or ID):

This would be a next step and followup PR. From the one I created you will see that I'm using the --cidfile option to podman which creates a file that contains the container id. The point here are the caller options to a program in the container. If they are the same you restart what you already have, if they differ you need a new container. This information I would simple encode in the CID file name turning the caller options into a hash value. That solves the issue and you will never have to ask a user which container to attach, either there is the appropriate one or you need a new one. But this will be a followup change after the open PR is merged

**Comment by schaefi** [comment]
> The point here are the caller options to a program in the container. If they are the same you restart what you already have, if they differ you need a new container. This information I would simple encode in the CID file name ...

done now
