### ISSUE TITLE
Support user assignment for flakes

### ISSUE THREAD

**Issue by isbm** [Elektrobit/oci-pilot#33]
If a Flake requires a root access, instead it will do something like:
```
Error: short-name "elektrobit/amd64_sdk" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

Calling this with `sudo ....` solves the issue. Probably we have to do the following:
1. If a Flake requires `sudo`, it should call it on its own with `sudo`. This could be set as an option in a corresponding Flake YAML config.
2. If `sudo` failed (user denied), then gracefully tell the user "sorry, you need to have `sudo` access, ask your admin"
3. I would not pre-check if sudo rights are there, but just go and call stuff with `sudo` and just "crash", gracefully wrapping the output, if no access.

**Comment by schaefi** [comment]
No this has nothing to do with oci-pilot at all. This is a pure podman setup "issue" on the host where podman is used.
In root mode ```/etc/containers/registries.conf``` is used. In rootless mode this information is read from the users home directory ```HOME/.config/containers/registries.conf```

See: https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md

Also with rootless the container registry is specific to the user. Each user can manage its own set of containers in its own registry with its own podman configuration files.

your sudo suggestion is not a solution to this behavior and oci-pilot has no responsibility to check this.

It can be very confusing if oci-pilot messes with this.

The only really good solution to this is to connect the flake config to a user like this:

```yaml
container: foo
target_app_path: path/to/program/in/container
host_app_path: path/to/program/on/host
run_as: USERNAME
```

and then oci-pilot has to run podman under the given user identity. If the user is root we can then use ```sudo podman``` if not we need to call ```su user podman ...```

All this is not a bug but an enhancement

**Comment by isbm** [comment]
Mmm... I fail to put all that together, TBH. If you use no `sudo`, it is trying to read `/etc/containers/registries.conf`, finds nothing configured and then crash. Why it then works with `sudo` if the `/etc/containers/registries.conf` is still empty and none of these in user home or `/root` home?

**Comment by schaefi** [comment]
ok I can explain that. If oci-pilot launches it calls ```podman run ...``` podman now reads the local registry and tries to find the container configured in the flake. If you run as ```sudo``` the registry for the root user is looked up. If you run as ```normal user``` the user's registry is looked up.

If you run as normal user and that user doesn't have the container loaded in its registry, the ```podman run``` behavior is to lookup the container in some other registry. The list of registries to lookup is as explained above. If there is no registries.conf at the end of all the lookup, podman comes up with that error message you saw

It would be imho better if podman just says "no such container for user XYZ"

Maybe we should add that check in oci-pilot prior calling ```podman run```

So your finding is imho two fold:

* oci-pilot should be able to assign the call to a user
* oci-pilot should have a check if local registry for the calling user has the container loaded

It would probably solve a lot of your confusion

**Comment by isbm** [comment]
That will be a big problem if a system-wide flake will require its copy for each user.

**Comment by schaefi** [comment]
I think this is a misunderstanding. A system wide flake in our case comes from a package. A package is installed as root. Thus the loading of the oci image happens as root. Therefore the container exists in the registry for root. Therefore this container can be started as root or via sudo.

My suggestion is that we run any podman command as:

```
sudo -u username
```

and username is a config setting in the flake config and defaults to root

I'm not suggesting that we copy the container image into each user registry. That would be a major pain and duplicating a million bytes and also producing forks all over the place.

* I think it should still be possible to allow user specific containers and oci-pilot registrations for it.
* Via ```/etc/sudoers``` a system can control which users are eligible to run system wide flakes.

From my perspective that is a flexible solution for everyone

I will create a pull request for this and then we can play a bit for a different scenarios
